"""initial schema

Revision ID: 385ebaaaaab5
Revises:
Create Date: 2026-08-26 06:56:14.889387

Piezas manuales anadidas sobre el autogenerate (PARTE 12 G1): extension
timescaledb, conversion a hypertable de trade/equity_snapshot/heartbeat_log,
compresion/retencion, continuous aggregate equity_daily, y el rol de
aplicacion `stratos_app` (P6/P15.3: SELECT/INSERT/UPDATE/DELETE en tablas
mutables, solo SELECT/INSERT en las 6 inmutables). La password del rol viene
de la env var APP_DB_PASSWORD en tiempo de migracion (nunca literal aqui);
se usa `exec_driver_sql` con escapado manual de comillas porque Postgres no
acepta bind params ($1) dentro de sentencias DDL como CREATE ROLE (probado
en esta sesion: falla con "syntax error at or near $1").
"""

from typing import Sequence, Union

from core.config import get_settings
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '385ebaaaaab5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

IMMUTABLE_TABLES = (
    "decision_log",
    "ingest_batch",
    "semaphore_transition",
    "killswitch_event",
    "withdrawal_log",
    "checklist_run",
)


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('broker', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('server', sa.String(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('connector_instance_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.Enum('INFO', 'SUAVE', 'CRITICA', name='alert_level'), nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('action_required', sa.Text(), nullable=True),
    sa.Column('dedup_key', sa.String(), nullable=True),
    sa.Column('resolved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checklist_type', sa.Enum('SUNDAY', 'BIWEEKLY', 'MONTHLY', 'QUARTERLY', 'ANNUAL', name='checklist_type'), nullable=False),
    sa.Column('period_key', sa.String(), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('signed_by', sa.String(), nullable=True),
    sa.Column('signature_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checklist_type', 'period_key')
    )
    op.create_table('decision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('instruction_text', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'POSTPONED', 'DISMISSED', name='decision_status'), server_default='PENDING', nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(), nullable=True),
    sa.Column('postpone_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.Enum('SYSTEM', 'HUMAN', name='actor_type'), nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('decision_type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fx_rate',
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('base', sa.String(length=3), nullable=False),
    sa.Column('quote', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.PrimaryKeyConstraint('ts', 'base', 'quote')
    )
    op.create_table('killswitch_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('portfolio_dd_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('instruction_text', sa.Text(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('impact', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='news_impact'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('blackout_before_min', sa.Integer(), server_default='30', nullable=False),
    sa.Column('blackout_after_min', sa.Integer(), server_default='30', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_config',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('ums_phase_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('phase', sa.Integer(), nullable=False),
    sa.Column('equity_at', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ready_to_advance', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), server_default='operator', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('withdrawal_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('equity_before', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('checklist_completed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('magic_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('profile', sa.Enum('TREND', 'MOMENTUM', 'MEAN_REVERSION', 'GRID', 'SCALPING', 'SMART_MONEY', 'AI_ML', name='bot_profile'), nullable=False),
    sa.Column('role', sa.Enum('CHAMPION', 'CHALLENGER', name='bot_role'), nullable=False),
    sa.Column('slot', sa.String(), nullable=True),
    sa.Column('pipeline_phase', sa.Enum('F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'PRODUCCION', 'CEMENTERIO', name='pipeline_phase'), nullable=False),
    sa.Column('semaphore_state', sa.Enum('VERDE', 'AMARILLO', 'NARANJA', name='semaphore_state'), server_default='VERDE', nullable=False),
    sa.Column('entered_state_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capital_allocated_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('risk_per_trade_pct', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('sizing_multiplier', sa.Numeric(precision=4, scale=2), server_default='1.0', nullable=False),
    sa.Column('sizing_current_pct', sa.Numeric(precision=4, scale=2), server_default='100.0', nullable=False),
    sa.Column('kelly_fraction', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('baseline_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['baseline_id'], ['baseline.id'], name='fk_bot_baseline_id', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'magic_number')
    )
    op.create_table('equity_snapshot',
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('equity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('drawdown_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('margin_level', sa.Float(), nullable=True),
    sa.Column('free_margin', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('ts', 'account_id')
    )
    op.create_table('heartbeat_log',
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('connector_instance_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('ts', 'connector_instance_id', 'account_id')
    )
    op.create_table('ingest_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('connector_instance_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('batch_type', sa.String(), nullable=False),
    sa.Column('records', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('server_ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('baseline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('BACKTEST', 'HISTORICO', name='baseline_source'), nullable=False),
    sa.Column('profit_factor', sa.Float(), nullable=False),
    sa.Column('expectancy_r', sa.Float(), nullable=False),
    sa.Column('sharpe', sa.Float(), nullable=False),
    sa.Column('max_dd_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('payoff', sa.Float(), nullable=False),
    sa.Column('avg_trade_duration_min', sa.Float(), nullable=False),
    sa.Column('max_consec_losses', sa.Integer(), nullable=False),
    sa.Column('expected_trades_30d', sa.Integer(), nullable=False),
    sa.Column('dd_contract_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cemetery_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cause', sa.Enum('ALPHA_DECAY', 'OVERFITTING', 'REGIME_CHANGE', 'BROKER_UNFAVORABLE', 'OUTPERFORMED_BY_CHALLENGER', 'COMPETITIVE_NOT_SUPERIOR', 'OTHER', name='cemetery_cause'), nullable=False),
    sa.Column('autopsy_text', sa.Text(), nullable=False),
    sa.Column('lesson', sa.Text(), nullable=False),
    sa.Column('revalidation_from_phase', sa.Enum('F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'PRODUCCION', 'CEMENTERIO', name='pipeline_phase'), server_default='F3', nullable=False),
    sa.Column('reactivation_blocked', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_id')
    )
    op.create_table('challenger_evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('challenger_bot_id', sa.Integer(), nullable=False),
    sa.Column('champion_bot_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.String(), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['challenger_bot_id'], ['bot.id'], ),
    sa.ForeignKeyConstraint(['champion_bot_id'], ['bot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('correlation_matrix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bot_a_id', sa.Integer(), nullable=False),
    sa.Column('bot_b_id', sa.Integer(), nullable=False),
    sa.Column('correlation', sa.Float(), nullable=False),
    sa.Column('is_redundant_pair', sa.Boolean(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bot_a_id'], ['bot.id'], ),
    sa.ForeignKeyConstraint(['bot_b_id'], ['bot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts', 'bot_a_id', 'bot_b_id')
    )
    op.create_table('impulse_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('desired_action', sa.Enum('PAUSE_BOT', 'CLOSE_POSITION', 'INCREASE_RISK', 'DECREASE_RISK', 'OTHER', name='impulse_action'), nullable=False),
    sa.Column('executed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'EVALUATING', 'CLOSED', name='impulse_status'), server_default='PENDING', nullable=False),
    sa.Column('counterfactual_result_7d_eur', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('avoided_cost_eur', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('montecarlo_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('n_simulations', sa.Integer(), nullable=False),
    sa.Column('dd_p50', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('dd_p75', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('dd_p95', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('dd_contract_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('current_phase', sa.Enum('F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'PRODUCCION', 'CEMENTERIO', name='pipeline_phase'), nullable=False),
    sa.Column('entered_phase_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('incubation_days', sa.Integer(), nullable=False),
    sa.Column('oos_trades', sa.Integer(), nullable=False),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('expectancy_r', sa.Float(), nullable=True),
    sa.Column('sharpe', sa.Float(), nullable=True),
    sa.Column('max_dd_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('wfe', sa.Float(), nullable=True),
    sa.Column('trades_per_week', sa.Float(), nullable=True),
    sa.Column('gates_passed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('gates_total', sa.Integer(), server_default='7', nullable=False),
    sa.Column('provisional', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('verdict', sa.Enum('GO', 'HOLD', 'KILL', name='verdict'), nullable=True),
    sa.Column('verdict_reason', sa.Text(), nullable=True),
    sa.Column('decision_eta_days', sa.Integer(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_id')
    )
    op.create_table('semaphore_transition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('from_state', sa.Enum('VERDE', 'AMARILLO', 'NARANJA', name='semaphore_state'), nullable=False),
    sa.Column('to_state', sa.Enum('VERDE', 'AMARILLO', 'NARANJA', name='semaphore_state'), nullable=False),
    sa.Column('trigger_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('instruction_text', sa.Text(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('magic_number', sa.Integer(), nullable=False),
    sa.Column('ticket_mt5', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type', sa.Enum('BUY', 'SELL', name='trade_type'), nullable=False),
    sa.Column('volume', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('sl', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('tp', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('profit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('commission', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('swap', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('r_multiple', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('ingest_batch_id', sa.Integer(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['bot_id'], ['bot.id'], ),
    sa.ForeignKeyConstraint(['ingest_batch_id'], ['ingest_batch.id'], ),
    sa.PrimaryKeyConstraint('id', 'open_time'),
    sa.UniqueConstraint('ticket_mt5', 'open_time')
    )
    # ### end Alembic commands ###

    # --- TimescaleDB: hypertables, compresion, retencion (PARTE 5.2) ---
    op.execute("SELECT create_hypertable('trade', 'open_time')")
    op.execute("SELECT create_hypertable('equity_snapshot', 'ts')")
    op.execute("SELECT create_hypertable('heartbeat_log', 'ts')")

    op.execute(
        "ALTER TABLE trade SET (timescaledb.compress, timescaledb.compress_segmentby = 'bot_id')"
    )
    op.execute("SELECT add_compression_policy('trade', INTERVAL '90 days')")

    op.execute(
        "ALTER TABLE equity_snapshot SET (timescaledb.compress, "
        "timescaledb.compress_segmentby = 'account_id')"
    )
    op.execute("SELECT add_compression_policy('equity_snapshot', INTERVAL '30 days')")

    op.execute("SELECT add_retention_policy('heartbeat_log', INTERVAL '30 days')")

    # --- Continuous aggregate equity_daily (ultimo valor del dia por cuenta) ---
    op.execute(
        """
        CREATE MATERIALIZED VIEW equity_daily
        WITH (timescaledb.continuous) AS
        SELECT
            account_id,
            time_bucket('1 day', ts) AS day,
            last(equity, ts) AS equity,
            last(balance, ts) AS balance,
            last(drawdown_pct, ts) AS drawdown_pct
        FROM equity_snapshot
        GROUP BY account_id, day
        WITH NO DATA
        """
    )
    op.execute(
        """
        SELECT add_continuous_aggregate_policy('equity_daily',
            start_offset => INTERVAL '3 days',
            end_offset => INTERVAL '1 hour',
            schedule_interval => INTERVAL '1 hour')
        """
    )

    # --- Rol de aplicacion restringido (P6/P15.3) ---
    # Password desde env en tiempo de migracion; exec_driver_sql (no op.execute/
    # sa.text) porque Postgres no soporta bind params ($1) en DDL como
    # CREATE ROLE (verificado en esta sesion).
    app_password = get_settings().app_db_password
    escaped_password = app_password.replace("'", "''")
    bind = op.get_bind()
    bind.exec_driver_sql(f"CREATE ROLE stratos_app LOGIN PASSWORD '{escaped_password}'")
    bind.exec_driver_sql("GRANT USAGE ON SCHEMA public TO stratos_app")
    bind.exec_driver_sql(
        "GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO stratos_app"
    )
    bind.exec_driver_sql("GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO stratos_app")
    immutable_list = ", ".join(IMMUTABLE_TABLES)
    bind.exec_driver_sql(
        f"REVOKE UPDATE, DELETE ON {immutable_list} FROM stratos_app"
    )
    # Futuras tablas (migraciones siguientes, creadas por el mismo rol owner
    # que corre Alembic) heredan estos privilegios automaticamente.
    bind.exec_driver_sql(
        "ALTER DEFAULT PRIVILEGES IN SCHEMA public "
        "GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO stratos_app"
    )
    bind.exec_driver_sql(
        "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO stratos_app"
    )


def downgrade() -> None:
    bind = op.get_bind()
    bind.exec_driver_sql(
        "ALTER DEFAULT PRIVILEGES IN SCHEMA public "
        "REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM stratos_app"
    )
    bind.exec_driver_sql(
        "ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE USAGE, SELECT ON SEQUENCES FROM stratos_app"
    )
    bind.exec_driver_sql("DROP OWNED BY stratos_app")
    bind.exec_driver_sql("DROP ROLE IF EXISTS stratos_app")

    op.execute("DROP MATERIALIZED VIEW IF EXISTS equity_daily")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade')
    op.drop_table('semaphore_transition')
    op.drop_table('pipeline_candidate')
    op.drop_table('montecarlo_run')
    op.drop_table('impulse_log')
    op.drop_table('correlation_matrix')
    op.drop_table('challenger_evaluation')
    op.drop_table('cemetery_entry')
    op.drop_table('baseline')
    op.drop_table('ingest_batch')
    op.drop_table('heartbeat_log')
    op.drop_table('equity_snapshot')
    op.drop_table('bot')
    op.drop_table('withdrawal_log')
    op.drop_table('user')
    op.drop_table('ums_phase_log')
    op.drop_table('system_config')
    op.drop_table('news_event')
    op.drop_table('killswitch_event')
    op.drop_table('fx_rate')
    op.drop_table('decision_log')
    op.drop_table('decision')
    op.drop_table('checklist_run')
    op.drop_table('alert')
    op.drop_table('account')

    # Los DROP TABLE no borran los tipos ENUM que usaban (bug real
    # encontrado en esta sesion: un downgrade+upgrade fallaba con
    # 'type X already exists'). Se dropean explicitamente aqui.
    op.execute("DROP TYPE IF EXISTS bot_profile")
    op.execute("DROP TYPE IF EXISTS bot_role")
    op.execute("DROP TYPE IF EXISTS pipeline_phase")
    op.execute("DROP TYPE IF EXISTS semaphore_state")
    op.execute("DROP TYPE IF EXISTS alert_level")
    op.execute("DROP TYPE IF EXISTS baseline_source")
    op.execute("DROP TYPE IF EXISTS verdict")
    op.execute("DROP TYPE IF EXISTS trade_type")
    op.execute("DROP TYPE IF EXISTS impulse_action")
    op.execute("DROP TYPE IF EXISTS impulse_status")
    op.execute("DROP TYPE IF EXISTS cemetery_cause")
    op.execute("DROP TYPE IF EXISTS checklist_type")
    op.execute("DROP TYPE IF EXISTS actor_type")
    op.execute("DROP TYPE IF EXISTS news_impact")
    op.execute("DROP TYPE IF EXISTS decision_status")
    # ### end Alembic commands ###
